### ISSUE TITLE
Startup/Shutdown options require the up_delay and down_delay to be set up

### ISSUE THREAD

**Issue by yoshikakbudto** [muhlba91/pulumi-proxmoxve#107]
In the provider all three parameters for the startup/shutdown are optional. You can see it in its code [here](https://github.com/bpg/terraform-provider-proxmox/pull/445/commits/4497b16e6acfb24ed860c9b312adeec6dab5f9de#diff-12bcc7e08b8cbd66ab84826d19fa7875cc1ce8acda247d75e508a3835ace5c15R3075)

But when i configure in pulumi only the `order` option, the up_delay and down_delay required to be set up:
```
proxmox.vm.VirtualMachine(
        startup=proxmox.vm.VirtualMachineStartupArgs(order=1),
  ...
```        

And when running pulumi up:
```
error: proxmoxve:VM/virtualMachine:VirtualMachine resource 'pve-b8-k8s-worker' has a problem: expected up_delay to be at least (0), got -1. Examine values at 'pve-b8-k8s-worker.startup.upDelay'.
error: proxmoxve:VM/virtualMachine:VirtualMachine resource 'pve-b8-k8s-worker' has a problem: expected down_delay to be at least (0), got -1. Examine values at 'pve-b8-k8s-worker.startup.downDelay'.
```

Also i need to configure ALL of the `VirtualMachineStartupArgs` parameters for the Shutdown/Startup options be actually applyed. I.e. 
```
        startup=proxmox.vm.VirtualMachineStartupArgs(order=1, down_delay=1, up_delay=1)
```

**Expected behaviour**

Any `proxmox.vm.VirtualMachineStartupArgs` should be optional.

**Comment by muhlba91** [comment]
can you please verify, and open an issue for this in the upstream provider? (https://github.com/bpg/terraform-provider-proxmox)

**Comment by muhlba91** [comment]
i have tested the startup order with the newest version, and the default values are the same as in Terraform: `-1`.

i have tested this with the newest Proxmox version. maybe there's a difference in Proxmox between versions?

btw. because of the way Pulumi computes the diff, it will take the plan generated by Terraform.
hence, you need to either set these values to the same (`-1`) or add them to the `ignoreDifferences` parameter if you don't want to have an "update" every time.

**Comment by muhlba91** [comment]
closing as it is fixed upstream.
