### ISSUE TITLE
Are there any plans on supporting LXC containers?

### ISSUE THREAD

**Issue by AnderssonPeter** [muhlba91/pulumi-proxmoxve#111]
Hi are there any plans on supporting creation of LXC containers?

**Comment by muhlba91** [comment]
The used upstream provider supports containers: https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_container

These Terraform resources are mapped to Pulumi ones. Hence, there is an existing resource for creating a container.

Does this meet your needs? Otherwise, I‘d ask you to open an issue upstream to add the specific features needed: https://github.com/bpg/terraform-provider-proxmox

**Comment by AnderssonPeter** [comment]
Thanks!
