### ISSUE TITLE
Add more container input properties

### ISSUE THREAD

**Issue by NCRoxas** [muhlba91/pulumi-proxmoxve#18]
It would be great if more container properties could be added like unprivileged and nesting.

**Comment by muhlba91** [comment]
since version `2.5.0` upstream also support `nesting`; `unprivileged` was available before already.

`unprivileged` can be set directly in the container arguments: https://github.com/muhlba91/pulumi-proxmoxve/blob/main/sdk/nodejs/ct/container.ts#L305

`nesting` must be set via the `features` argument: https://github.com/muhlba91/pulumi-proxmoxve/blob/main/sdk/nodejs/ct/container.ts#L265 (https://github.com/muhlba91/pulumi-proxmoxve/blob/main/sdk/nodejs/types/input.ts#L45)
