### ISSUE TITLE
How to print the local IP out that qemu-guest-agent displays?

### ISSUE THREAD

**Issue by jebarpg** [muhlba91/pulumi-proxmoxve#327]
Currently I'm creating a vm

```
 const virtualMachine = new proxmox.vm.VirtualMachine('vm' + i, {
...
...
})
```

Then right afterwards doing

`console.log(virtualMachine.ipv4Addresses)`

and the output I get is:

```
OutputImpl {
      __pulumiOutput: true,
      resources: [Function (anonymous)],
      allResources: [Function (anonymous)],
      isKnown: Promise { <pending> },
      isSecret: Promise { <pending> },
      promise: [Function (anonymous)],
      toString: [Function (anonymous)],
      toJSON: [Function (anonymous)]
    }
```

I'm not sure what else to do to get the local ip address. Any help is appreciate!

Cheers

**Comment by muhlba91** [comment]
the attribute `ipv4Addresses` is a Pulumi output object. for example, you need to call `apply` on it to retrieve the plain text value:

```
vm.ipv4Addresses.apply((addr) => console.log(addr));
```

`ipv4Addresses` is an array though and you need to take care that it's not filled from the beginning. for example, in one of my VMs this array looks similar to this: `[[10.0.0.1], [], [10.10.0.1], [10.10.0.2], [], ...]`

additionally, as you can see this array is an array of arrays, representing the ip addresses per network interface. if you have, e.g., docker or kubernetes running you'll end up with many interfaces and will need to be precise with what ip address you want.
also, you need to set the `agent.enabled` flag to `true`; otherwise, it will be an empty array.

another way is to use cloud-init ready images with the `initialization` block. for example, i use the generic-cloud debian image, and set the ip addresses in this block. that ensures my VM always gets the same address and i can be specific about it as well.

**Comment by jebarpg** [comment]
Thank you! This is very helpful.

**Comment by jebarpg** [comment]
O also in addition you need 
`started: true,
`
otherwise the qemu-guest-agent is never ran on the machine... just for anyone in the future who reads this.
